name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with exceptions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          ini-values: opcache.enable_cli=0, opcache.enable=0
          extensions: mbstring

      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --working-dir=${GITHUB_WORKSPACE}/test --prefer-dist --no-progress

      - name: Run test web servers
        run: sh ${GITHUB_WORKSPACE}/test/initservers.sh

      - name: Check test servers health
        run: curl -v http://localhost:3000

      - name: Run wait until servers are ready
        run: sleep 15

      - name: Run tests
        run: php ${GITHUB_WORKSPACE}/test/vendor/phpunit/phpunit/phpunit --configuration ${GITHUB_WORKSPACE}/test/phpunit.xml
